services:
  eureka-server:
    build:
      context: ./eureka-server-app
    container_name: eureka_service
    ports:
      - '8761:8761'
    environment:
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: 'false'
      EUREKA_CLIENT_FETCH_REGISTRY: 'false'
    restart: unless-stopped

  postgres-db:
    image: 'postgres:15-alpine'
    container_name: pg_auth_service
    environment:
      POSTGRES_DB: db_restaurant_auth
      POSTGRES_USER: usr_auth_service
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - '5432:5432'
    volumes:
      - pg_data_auth:/var/lib/postgresql/data
    secrets:
      - db_password
    restart: unless-stopped

  auth-service:
    build:
      context: ./auth-service-app
    container_name: auth_service
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/db_restaurant_auth
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
      # O segredo é mapeado para a variável que o YAML espera
      DB_PASSWORD: /run/secrets/db_password
    depends_on:
      - postgres-db
      - eureka-server
    secrets:
      - db_password
    restart: unless-stopped

secrets:
  db_password:
    file: ./secrets/db_password.txt

volumes:
  pg_data_auth:
    driver: local