services:
  postgres-db:
    image: 'postgres:15-alpine'
    container_name: pg_auth_service
    environment:
      POSTGRES_DB: db_restaurant_auth
      POSTGRES_USER: usr_auth_service
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - '5432:5432'
    volumes:
      - pg_data_auth:/var/lib/postgresql/data
    secrets:
      - db_password
    restart: unless-stopped

  auth-service:
    build:
      context: . # Usa a pasta atual onde está o seu src/ e pom.xml
    container_name: auth_service
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/db_restaurant_auth
      DB_PASSWORD: /run/secrets/db_password
    depends_on:
      - postgres-db # Removido o eureka-server daqui
    secrets:
      - db_password
    restart: unless-stopped

secrets:
  db_password:
    file: ./secrets/db_password.txt

volumes:
  pg_data_auth:
    driver: local