server:
  port: 8080
  servlet:
    context-path: /user-service

spring:
  application:
    name: user-service
  cloud:
    config:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    # Conecta ao PostgreSQL no seu Ubuntu
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://192.168.137.2:5432/db_restaurant_auth}
    username: usr_auth_service
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    schemas: public  # Force o Flyway a usar o schema public
    default-schema: public
    locations: classpath:db/migration

  jpa:
    hibernate:
      # 'validate' para que o Flyway controle o esquema
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

# Configuração do SpringDoc para usar arquivo YAML externo
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi.yaml
  override-with-generic-response: true

api:
  security:
    token:
      secret: ${JWT_SECRET:minha-chave-secreta-muito-segura-123456}

logging:
  level:
    root: INFO
    br.com.user.service.auth: DEBUG # Mostra detalhes apenas do seu projeto
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
